create table if not exists public.starred_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  message_id text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists starred_messages_user_message_unique
  on public.starred_messages (user_id, message_id);

create index if not exists starred_messages_user_created_idx
  on public.starred_messages (user_id, created_at desc);

alter table public.starred_messages enable row level security;

drop policy if exists "Users can read own starred messages" on public.starred_messages;
create policy "Users can read own starred messages"
  on public.starred_messages for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own starred messages" on public.starred_messages;
create policy "Users can insert own starred messages"
  on public.starred_messages for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own starred messages" on public.starred_messages;
create policy "Users can delete own starred messages"
  on public.starred_messages for delete
  to authenticated
  using (auth.uid() = user_id);

grant select, insert, delete on table public.starred_messages to authenticated;
grant usage, select on sequence public.starred_messages_id_seq to authenticated;
